// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "home": {
    "title": "Dashboard",
    "welcome": "Welcome to Rzev Dashboard",
    "logout": "Logout"
  },
  "navbar": {
    "logoText": "Rzev",
    "loginSignup": "Login / Sign Up",
    "customersPortal": "Customers Portal",
    "professionalsPortal": "Professionals Portal"
  },
  "auth": {
    "title": "Welcome Back",
    "subtitle": "Sign in to your account to continue",
    "loginTo": "Login to your",
    "workspace": "Workspace",
    "emailTab": "Email",
    "loading": "Loading...",
    "checkEmailVerify": "Please check your email for a verification link.",
    "accountCreated": "Account created",
    "socialLoginDetected": "Social login detected",
    "useSocialProvider": "You are using {provider}. Please use {provider} to log in.",
    "googleTab": "Google",
    "email": "Email",
    "password": "Password",
    "backToHome": "Back to home",
    "backToEmail": "Back to email",
    "createAccount": "Create Account",
    "creatingAccount": "Creating account...",
    "forgotPassword": "Forgot password?",
    "signIn": "Sign In",
    "continue": "Continue",
    "firstName": "First Name",
    "lastName": "Last Name",
    "phone": "Phone",
    "orContinueWith": "or continue with",
    "googleSignIn": "Sign in with Google",
    "termsText": "By signing in, you agree to our",
    "termsLink": "Terms of Service",
    "privacyLink": "Privacy Policy",
    "orUse": "or use",
    "useMagicLink": "Sign in with Magic Link",
    "sendingMagicLink": "Sending Magic Link...",
    "magicLinkSent": "Magic Link Sent",
    "magicLinkInstructions": "Check your email for a login link. The link will expire in 10 minutes.",
    "magicLinkError": "Could not send magic link. Please try again.",
    "error": "Error",
    "emailCheckError": "Could not check email. Please try again.",
    "emailNotVerified": "Email not verified",
    "emailVerificationRequired": "Please check your email for a verification link.",
    "signInError": "Sign in error",
    "checkCredentials": "Please check your credentials and try again.",
    "callback": {
      "title": "Confirmation",
      "confirming": "Confirming your third party login account...",
      "success": "✅ Your account is confirmed! You can now log in.",
      "error": "❌ Something went wrong confirming your account.",
      "missingToken": "Missing token information from confirmation link.",
      "sessionError": "Session Error",
      "redirecting": "Redirecting to your profile..."
    },
    "confirmEmail": {
      "title": "Confirmation",
      "confirming": "Confirming your email...",
      "success": "✅ Your email is confirmed! You can now log in.",
      "error": "❌ Something went wrong confirming your email.",
      "missingToken": "Missing token information from confirmation link.",
      "sessionError": "Session Error",
      "redirecting": "Redirecting to your profile..."
    }
  },
  "common": {
    "loading": "Loading...",
    "error": "Error",
    "success": "Success",
    "save": "Save",
    "cancel": "Cancel",
    "edit": "Edit",
    "delete": "Delete",
    "confirm": "Confirm",
    "back": "Back",
    "isRequired": "is required",
    "enterValidUrl": "Please enter a valid URL",
    "placeholder": "This is a placeholder for future implementation"
  },
  "nav": {
    "dashboard": "Dashboard",
    "profile": "Profile",
    "settings": "Settings",
    "logout": "Logout"
  },
  "onboarding": {
    "title": "Complete Your",
    "businessSetup": "Business Setup",
    "common": {
      "isRequired": "is required",
      "enterValidUrl": "Please enter a valid URL"
    },
    "steps": {
      "businessInfo": "Business Info",
      "servicesOffer": "Services",
      "teamSize": "Team",
      "serviceLocations": "Locations",
      "businessLocation": "Business Address",
      "currentSoftware": "Current Software",
      "heardAboutUs": "Referral",
      "complete": "Complete"
    },
    "navigation": {
      "back": "Back",
      "next": "Next",
      "skip": "Skip",
      "finish": "Finish"
    },
    "businessInfo": {
      "title": "Business Information",
      "description": "Tell us about your business",
      "businessNameLabel": "Business Name",
      "businessNamePlaceholder": "Enter your business name",
      "websiteLabel": "Website (Optional)",
      "websitePlaceholder": "https://yourbusiness.com"
    },
    "servicesOffer": {
      "title": "Services You Offer",
      "description": "What services does your business provide?",
      "selectInstruction": "Select all services that your business offers. You can update these later.",
      "servicesSelected": "{count} service selected",
      "servicesSelectedPlural": "{count} services selected",
      "otherServiceLabel": "Specify Other Service",
      "otherServicePlaceholder": "Please specify your other service",
      "selectionRequired": "Please select at least one service",
      "otherServiceRequired": "Please specify your other service",
      "categories": {
        "hair": "Hair",
        "nails": "Nails",
        "makeup": "Makeup",
        "skincare": "Skincare",
        "massage": "Massage",
        "spa": "Spa",
        "barber": "Barber",
        "waxing": "Waxing",
        "lashes": "Lashes & Brows",
        "tanning": "Tanning",
        "tattoo": "Tattoo",
        "piercing": "Piercing",
        "fitness": "Fitness",
        "yoga": "Yoga",
        "wellness": "Wellness",
        "nutrition": "Nutrition",
        "therapy": "Therapy",
        "dental": "Dental",
        "medical": "Medical",
        "other": "Other"
      }
    },
    "teamSize": {
      "title": "Team Size",
      "description": "How many people are in your team?",
      "selectionRequired": "Please select a team size option",
      "options": {
        "individual": "Individual",
        "individualDescription": "Just you working alone",
        "small": "Small Team (2-6)",
        "smallDescription": "You and a few team members",
        "large": "Large Team (7+)",
        "largeDescription": "You and a larger team"
      }
    },
    "serviceLocations": {
      "title": "Service Locations",
      "description": "Where do you provide your services?",
      "selectionRequired": "Please select at least one service location option",
      "options": {
        "inStore": "In-Store",
        "inStoreDescription": "Clients come to your location for services",
        "clientLocation": "Client's Location",
        "clientLocationDescription": "You travel to the client's location",
        "both": "Both",
        "bothDescription": "You offer services both in-store and at client locations"
      }
    },
    "businessLocation": {
      "title": "Business Location",
      "description": "Enter your business address where clients will visit you",
      "addressLabel": "Address",
      "addressPlaceholder": "Start typing your address",
      "addressRequired": "Business address is required",
      "addressLine1Label": "Address Line 1",
      "addressLine1Placeholder": "123 Main Street",
      "addressLine2Label": "Address Line 2 (Optional)",
      "addressLine2Placeholder": "Suite 100, Floor 2, etc.",
      "cityLabel": "City",
      "cityPlaceholder": "Enter city",
      "stateLabel": "State/Province",
      "statePlaceholder": "Enter state or province",
      "postalCodeLabel": "Postal Code",
      "postalCodePlaceholder": "Enter postal code",
      "countryLabel": "Country",
      "countryPlaceholder": "Select country",
      "validationError": "Please enter a valid address",
      "addressNotFound": "Address not found. Please try again."
    },
    "currentSoftware": {
      "title": "Which software are you currently using?",
      "description": "If you're looking to switch, we can help speed up your business setup and import your data into your new Rzev account.",
      "selectionRequired": "Please select a software option",
      "otherSoftwareRequired": "Please specify the other software you are using",
      "otherSoftwareLabel": "Please specify the software you are using",
      "otherSoftwarePlaceholder": "Enter the name of your current software",
      "options": {
        "acuity": "Acuity",
        "booksy": "Booksy",
        "calendly": "Calendly",
        "clover": "Clover",
        "goldie": "Goldie",
        "glossGenius": "Gloss Genius",
        "janeapp": "Janeapp",
        "mangomint": "Mangomint",
        "mindbody": "Mindbody",
        "ovatu": "Ovatu",
        "phorest": "Phorest",
        "square": "Square",
        "salonIris": "Salon Iris",
        "setmore": "Setmore",
        "shortcuts": "Shortcuts",
        "squire": "Squire",
        "styleseat": "Styleseat",
        "timely": "Timely",
        "vagaro": "Vagaro",
        "zenoti": "Zenoti",
        "none": "I'm not using any software",
        "other": "Other"
      }
    },
    "heardAboutUs": {
      "title": "How Did You Hear About Us?",
      "description": "We'd love to know how you discovered our platform",
      "pleaseSpecify": "Please specify:",
      "otherPlaceholder": "Please tell us how you heard about us",
      "selectionRequired": "Please select how you heard about us",
      "otherSourceRequired": "Please specify how you heard about us",
      "options": {
        "friend": "Recommended by a friend",
        "search": "Search engine (e.g. Google, Bing)",
        "social": "Social media",
        "mail": "Advert in the mail",
        "magazine": "Magazine ad",
        "ratings": "Ratings website (e.g. Capterra, Trustpilot)",
        "other": "Other"
      }
    },
    "submitting": "Saving...",
    "successTitle": "Setup Complete",
    "successMessage": "Your business profile has been set up successfully",
    "errorTitle": "Setup Failed",
    "errorMessage": "There was an error setting up your business profile. Please try again."
  },
  "dashboard": {
    "sidebar": {
      "title": "Rzev Dashboard",
      "merchantAccount": "Merchant Account",
      "signOut": "Sign Out",
      "navigation": {
        "dashboard": "Dashboard",
        "calendar": "Calendar",
        "clients": "Clients",
        "team": "Team",
        "subscriptions": "Subscriptions",
        "analytics": "Analytics",
        "messages": "Messages",
        "services": "Services",
        "settings": "Settings"
      }
    },
    "calendar": {
      "title": "Calendar",
      "subtitle": "Manage your appointments and team schedule",
      "time": "Time",
      "day": "Day",
      "week": "Week",
      "selectTeamMember": "Select team member",
      "allTeamMembers": "All Team Members",
      "available": "Available",
      "showingSchedule": "Showing schedule for {count} team member(s)",
      "appointmentDetails": {
        "title": "Appointment Details",
        "subtitle": "View the details of this appointment",
        "customer": "Customer",
        "service": "Service",
        "date": "Date",
        "time": "Time",
        "staff": "Staff",
        "status": "Status",
        "confirmed": "Confirmed",
        "reschedule": "Reschedule",
        "cancel": "Cancel Appointment",
        "duration": "{duration} min"
      }
    },
    "clients": {
      "title": "Clients",
      "subtitle": "Manage your client database and information",
      "clientList": "Client List",
      "clientListDescription": "View and manage all your clients",
      "searchPlaceholder": "Search clients...",
      "addClient": "Add Client",
      "comingSoon": "Client management coming soon"
    },
    "team": {
      "title": "Team",
      "subtitle": "Manage your team members and their schedules",
      "teamMembers": "Team Members",
      "teamMembersDescription": "View and manage your team",
      "searchPlaceholder": "Search team...",
      "addTeamMember": "Add Team Member",
      "noTeamMembers": "No team members found",
      "common": {
        "loading": "Loading...",
        "success": "Success",
        "error": "Error",
        "edit": "Edit",
        "delete": "Delete",
        "noEmail": "No email"
      },
      "addTeamMemberForm": {
        "title": "Add Team Member",
        "editTitle": "Edit Team Member",
        "name": "Name",
        "namePlaceholder": "Enter team member name",
        "email": "Email",
        "emailPlaceholder": "Enter team member email",
        "role": "Role",
        "rolePlaceholder": "Select role",
        "roles": {
          "admin": "Admin",
          "manager": "Manager",
          "staff": "Staff"
        },
        "active": "Active",
        "add": "Add Team Member",
        "update": "Update Team Member",
        "cancel": "Cancel"
      },
      "availability": {
        "title": "Availability",
        "addAvailability": "Add Availability",
        "editAvailability": "Edit Availability",
        "dayOfWeek": "Day of Week",
        "startTime": "Start Time",
        "endTime": "End Time",
        "available": "Available",
        "days": {
          "sunday": "Sunday",
          "monday": "Monday",
          "tuesday": "Tuesday",
          "wednesday": "Wednesday",
          "thursday": "Thursday",
          "friday": "Friday",
          "saturday": "Saturday"
        },
        "noAvailability": "No availability set",
        "add": "Add",
        "update": "Update",
        "cancel": "Cancel",
        "delete": "Delete"
      },
      "deleteConfirmation": {
        "title": "Delete Team Member",
        "message": "Are you sure you want to delete this team member? This action cannot be undone.",
        "confirm": "Delete",
        "cancel": "Cancel"
      },
      "notifications": {
        "addSuccess": "Team member added successfully",
        "updateSuccess": "Team member updated successfully",
        "deleteSuccess": "Team member deleted successfully",
        "error": "An error occurred",
        "availabilityAddSuccess": "Availability added successfully",
        "availabilityUpdateSuccess": "Availability updated successfully",
        "availabilityDeleteSuccess": "Availability deleted successfully"
      }
    },
    "subscriptions": {
      "title": "Subscriptions",
      "subtitle": "Manage your subscription plans and billing",
      "tabs": {
        "plans": "Subscription Plans",
        "billing": "Billing History",
        "settings": "Payment Settings"
      },
      "plans": {
        "basic": {
          "name": "Basic",
          "description": "For small businesses just getting started",
          "price": "$29",
          "period": "/month",
          "features": {
            "0": "Up to 100 appointments/month",
            "1": "2 team members",
            "2": "Basic analytics",
            "3": "Email notifications",
            "length": "4"
          },
          "button": "Current Plan"
        },
        "professional": {
          "name": "Professional",
          "description": "For growing businesses with more needs",
          "price": "$79",
          "period": "/month",
          "badge": "Popular",
          "features": {
            "0": "Unlimited appointments",
            "1": "Up to 5 team members",
            "2": "Advanced analytics",
            "3": "Email & SMS notifications",
            "4": "Custom branding",
            "length": "5"
          },
          "button": "Upgrade Plan"
        },
        "enterprise": {
          "name": "Enterprise",
          "description": "For large businesses with advanced requirements",
          "price": "$199",
          "period": "/month",
          "features": {
            "0": "Unlimited everything",
            "1": "Unlimited team members",
            "2": "Priority support",
            "3": "Advanced integrations",
            "4": "Dedicated account manager",
            "length": "5"
          },
          "button": "Contact Sales"
        }
      },
      "comingSoon": {
        "billing": "Billing history coming soon",
        "settings": "Payment settings coming soon"
      }
    },
    "analytics": {
      "title": "Analytics",
      "subtitle": "Track your business performance and growth",
      "periods": {
        "selectPeriod": "Select period",
        "7days": "Last 7 days",
        "30days": "Last 30 days",
        "90days": "Last 90 days",
        "year": "This year",
        "custom": "Custom range"
      },
      "tabs": {
        "overview": "Overview",
        "revenue": "Revenue",
        "appointments": "Appointments",
        "clients": "Clients",
        "team": "Team"
      },
      "metrics": {
        "totalRevenue": "Total Revenue",
        "appointments": "Appointments",
        "newClients": "New Clients",
        "conversionRate": "Conversion Rate",
        "fromLastPeriod": "+{percent}% from last period"
      },
      "charts": {
        "revenueTrend": "Revenue Trend",
        "revenueTrendDesc": "Monthly revenue for the last 12 months",
        "appointmentDistribution": "Appointment Distribution",
        "appointmentDistributionDesc": "Breakdown by service type",
        "comingSoon": "Coming soon",
        "revenueChartComing": "Revenue chart coming soon",
        "distributionChartComing": "Distribution chart coming soon",
        "revenueAnalyticsComing": "Detailed revenue analytics coming soon",
        "appointmentAnalyticsComing": "Appointment analytics coming soon",
        "clientAnalyticsComing": "Client analytics coming soon",
        "teamAnalyticsComing": "Team performance analytics coming soon"
      }
    },
    "messages": {
      "title": "Messages",
      "subtitle": "Communicate with your clients",
      "conversations": "Conversations",
      "searchPlaceholder": "Search messages...",
      "lastActive": "Last active: {time}",
      "messageHistoryComing": "Message history coming soon",
      "typePlaceholder": "Type your message..."
    },
    "services": {
      "title": "Services",
      "subtitle": "Manage your service offerings and pricing",
      "serviceList": "Service List",
      "serviceListDescription": "View and manage all your services",
      "searchPlaceholder": "Search services...",
      "addServiceTitle": "Add Service",
      "addServiceDescription": "Add a new service",
      "cancel": "Cancel",
      "serviceName": "Service Name",
      "serviceNamePlaceholder": "Enter service name",
      "serviceDescription": "Service Description",
      "serviceDescriptionPlaceholder": "Enter service description",
      "serviceCategory": "Service Category",
      "serviceCategoryPlaceholder": "Enter service category",
      "serviceDuration": "Service Duration",
      "servicePrice": "Service Price",
      "serviceActive": "Service Status",
      "serviceActiveDescription": "Enable or disable service",
      "adding": "Adding...",
      "editServiceTitle": "Edit Service",
      "editServiceDescription": "Edit existing service",
      "updateService": "Update Service",
      "deleteServiceTitle": "Delete Service",
      "deleteServiceDescription": "Delete existing service",
      "deleteService": "Delete Service",
      "addService": "Add Service",
      "name": "Name",
      "category": "Category",
      "duration": "{duration} min",
      "price": "Price",
      "actions": "Actions",
      "edit": "Edit",
      "delete": "Delete"
    },
    "settings": {
      "title": "Settings",
      "subtitle": "Manage your account and application preferences",
      "tabs": {
        "profile": "Profile",
        "business": "Business",
        "notifications": "Notifications",
        "security": "Security"
      },
      "common": {
        "loading": "Loading...",
        "success": "Success",
        "error": "Error"
      },
      "profile": {
        "title": "Profile Information",
        "subtitle": "Update your personal information",
        "fullName": "Full Name",
        "email": "Email",
        "emailCannotBeChanged": "Your email cannot be changed",
        "phone": "Phone Number",
        "role": "Role",
        "saveChanges": "Save Changes"
      },
      "business": {
        "title": "Business Information",
        "subtitle": "Update your business details",
        "businessName": "Business Name",
        "businessEmail": "Business Email",
        "businessPhone": "Business Phone",
        "website": "Website",
        "description": "Business Description",
        "descriptionPlaceholder": "Tell customers about your business...",
        "logo": "Business Logo",
        "uploadLogo": "Upload logo",
        "selectLogo": "Select Logo",
        "changeLogo": "Change Logo",
        "logoRequirements": "Recommended size: 400x400px. Max size: 2MB. Formats: JPEG, PNG, GIF, WEBP",
        "invalidFileType": "Invalid file type. Please upload a JPEG, PNG, GIF or WEBP image.",
        "fileTooLarge": "File is too large. Maximum size is 2MB.",
        "timezone": "Timezone",
        "selectTimezone": "Select a timezone",
        "timezoneDescription": "This timezone will be used for your business operations and scheduling.",
        "address": "Address",
        "city": "City",
        "state": "State",
        "zipCode": "ZIP Code",
        "saveChanges": "Save Changes",
        "saveSuccess": "Business information saved successfully",
        "saveError": "Error saving business information"
      },
      "notifications": {
        "title": "Notification Preferences",
        "subtitle": "Manage how you receive notifications",
        "emailNotifications": "Email Notifications",
        "appointmentNotifications": "Appointment Notifications",
        "appointmentNotificationsDesc": "Receive emails about new, updated, or canceled appointments",
        "appointmentReminders": "Appointment Reminders",
        "appointmentRemindersDesc": "Receive reminder emails before upcoming appointments",
        "marketingPromotions": "Marketing & Promotions",
        "marketingPromotionsDesc": "Receive emails about special offers and promotions",
        "smsNotifications": "SMS Notifications",
        "smsAppointmentNotifications": "Appointment Notifications",
        "smsAppointmentNotificationsDesc": "Receive SMS about new, updated, or canceled appointments",
        "smsAppointmentReminders": "Appointment Reminders",
        "smsAppointmentRemindersDesc": "Receive reminder SMS before upcoming appointments",
        "savePreferences": "Save Preferences"
      },
      "appearance": {
        "comingSoon": "Appearance settings coming soon"
      },
      "security": {
        "title": "Security Settings",
        "subtitle": "Manage your account security and password",
        "currentPassword": "Current Password",
        "newPassword": "New Password",
        "confirmPassword": "Confirm New Password",
        "passwordRequirements": "Must be at least 8 characters",
        "changePassword": "Change Password",
        "passwordChanged": "Password changed successfully",
        "passwordChangedLogout": "Password changed successfully. You will be logged out in a moment.",
        "changePasswordError": "Error changing password",
        "passwordTooShort": "Password must be at least 8 characters",
        "passwordsDontMatch": "Passwords don't match",
        "comingSoon": "Security settings coming soon",
        "socialLoginMessage": "You signed up with a social provider (Google). Please manage your password through your social provider's settings."
      }
    }
  }
};
export default messages;