// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "home": {
    "title": "Dashboard",
    "welcome": "Welcome to Rzev Dashboard",
    "logout": "Logout"
  },
  "navbar": {
    "logoText": "Rzev",
    "loginSignup": "Login / Sign Up",
    "customersPortal": "Customers Portal",
    "professionalsPortal": "Professionals Portal"
  },
  "auth": {
    "title": "Welcome Back",
    "subtitle": "Sign in to your account to continue",
    "loginTo": "Login to your",
    "workspace": "Workspace",
    "emailTab": "Email",
    "loading": "Loading...",
    "checkEmailVerify": "Please check your email for a verification link.",
    "accountCreated": "Account created",
    "socialLoginDetected": "Social login detected",
    "useSocialProvider": "You are using {provider}. Please use {provider} to log in.",
    "googleTab": "Google",
    "email": "Email",
    "password": "Password",
    "backToHome": "Back to home",
    "backToEmail": "Back to email",
    "createAccount": "Create Account",
    "creatingAccount": "Creating account...",
    "forgotPassword": "Forgot password?",
    "signIn": "Sign In",
    "continue": "Continue",
    "firstName": "First Name",
    "lastName": "Last Name",
    "phone": "Phone",
    "orContinueWith": "or continue with",
    "googleSignIn": "Sign in with Google",
    "termsText": "By signing in, you agree to our",
    "termsLink": "Terms of Service",
    "privacyLink": "Privacy Policy",
    "orUse": "or use",
    "useMagicLink": "Sign in with Magic Link",
    "sendingMagicLink": "Sending Magic Link...",
    "magicLinkSent": "Magic Link Sent",
    "magicLinkInstructions": "Check your email for a login link. The link will expire in 10 minutes.",
    "magicLinkError": "Could not send magic link. Please try again.",
    "error": "Error",
    "emailCheckError": "Could not check email. Please try again.",
    "emailNotVerified": "Email not verified",
    "emailVerificationRequired": "Please check your email for a verification link.",
    "signInError": "Sign in error",
    "checkCredentials": "Please check your credentials and try again.",
    "callback": {
      "title": "Confirmation",
      "confirming": "Confirming your third party login account...",
      "success": "✅ Your account is confirmed! You can now log in.",
      "error": "❌ Something went wrong confirming your account.",
      "missingToken": "Missing token information from confirmation link.",
      "sessionError": "Session Error",
      "redirecting": "Redirecting to your profile..."
    },
    "confirmEmail": {
      "title": "Confirmation",
      "confirming": "Confirming your email...",
      "success": "✅ Your email is confirmed! You can now log in.",
      "error": "❌ Something went wrong confirming your email.",
      "missingToken": "Missing token information from confirmation link.",
      "sessionError": "Session Error",
      "redirecting": "Redirecting to your profile..."
    }
  },
  "common": {
    "loading": "Loading...",
    "error": "Error",
    "success": "Success",
    "save": "Save",
    "cancel": "Cancel",
    "edit": "Edit",
    "delete": "Delete",
    "confirm": "Confirm",
    "back": "Back"
  },
  "nav": {
    "dashboard": "Dashboard",
    "profile": "Profile",
    "settings": "Settings",
    "logout": "Logout"
  }
};
export default messages;